project_name: k3d

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: '{{ if .IsSnapshot }}terraform-provider-{{ .ProjectName }}_v{{ .Version }}{{ else }}terraform-provider-{{ .ProjectName }}_{{ .Tag }}{{ end }}'

archives:
  - format: zip
    name_template: '{{ if .IsSnapshot }}terraform-provider-{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ else }}terraform-provider-{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ end }}'

checksum:
  name_template: '{{ if .IsSnapshot }}terraform-provider-{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS{{ else }}terraform-provider-{{ .ProjectName }}_{{ .Tag }}_SHA256SUMS{{ end }}'
  algorithm: sha256

snapshot:
  name_template: '0.1.0-{{ .ShortCommit }}'

changelog:
  skip: true

signs:
  - id: checksum
    artifacts: checksum
    signature: '${artifact}.sig'
    cmd: gpg
    args:
      - --batch
      - --pinentry-mode
      - loopback
      - --detach-sign
      - --armor
      - --output
      - '${signature}'
      - '${artifact}'
